/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.net.java.dev.jna.jna)
    api(libs.net.java.dev.jna.jna.platform)
    testImplementation(libs.junit.junit)
    testImplementation(libs.com.sun.xml.ws.jaxws.ri)
}

group = "com.googlecode.lanterna"
version = "3.2.5-SNAPSHOT"
description = "Lanterna"
java.sourceCompatibility = JavaVersion.VERSION_1_8

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier = "tests"
    from(sourceSets["test"].output)
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
        artifact(testsJar)
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
	  // https://docs.oracle.com/en/java/javase/11/javadoc/source-files.html#GUID-B984B421-ECE0-4FD8-9485-FC447B8201EB
    // https://stackoverflow.com/questions/52205209/configure-gradle-build-to-suppress-javadoc-console-warnings
		(options as CoreJavadocOptions).addStringOption("Xdoclint:none", "-quiet")
}
